export const CRM_FIELDS = {
  Candidate: [
    { label: 'Candidate Name', value: '{{candidateName}}' },
    { label: 'Candidate Email', value: '{{candidateEmail}}' },
    { label: 'Candidate Phone', value: '{{candidatePhone}}' },
    { label: 'Candidate ID', value: '{{candidateId}}' },
  ],
  Interview: [
    { label: 'Interview Date', value: '{{interviewDate}}' },
    { label: 'Interview Time', value: '{{interviewTime}}' },
    { label: 'Interview Mode', value: '{{interviewMode}}' },
    { label: 'Interview Round', value: '{{interviewRound}}' },
    { label: 'Panelist Name', value: '{{panelistName}}' },
    { label: 'Interview Link', value: '{{interviewLink}}' },
  ],
  Offer: [
    { label: 'Designation', value: '{{designation}}' },
    { label: 'Joining Date', value: '{{joiningDate}}' },
    { label: 'Annual CTC', value: '{{annualCTC}}' },
    { label: 'Offer Expiry', value: '{{offerExpiry}}' },
    { label: 'Department', value: '{{department}}' },
  ],
  Company: [
    { label: 'Company Name', value: '{{companyName}}' },
    { label: 'Company Address', value: '{{companyAddress}}' },
    { label: 'HR Name', value: '{{hrName}}' },
    { label: 'HR Email', value: '{{hrEmail}}' },
    { label: 'Company Logo URL', value: '{{companyLogo}}' },
    { label: 'Company Website', value: '{{companyWebsite}}' },
  ],
  Employee: [
    { label: 'Employee Name', value: '{{employeeName}}' },
    { label: 'Employee ID', value: '{{employeeId}}' },
    { label: 'Employee Email', value: '{{employeeEmail}}' },
    { label: 'Manager Name', value: '{{managerName}}' },
  ],
};

export const DUMMY_VALUES = {
  '{{candidateName}}': 'John Smith',
  '{{candidateEmail}}': 'john.smith@email.com',
  '{{candidatePhone}}': '+91 9876543210',
  '{{candidateId}}': 'CND-2026-001',
  '{{interviewDate}}': 'Monday, April 1, 2026',
  '{{interviewTime}}': '10:30 AM',
  '{{interviewMode}}': 'Video Call (Google Meet)',
  '{{interviewRound}}': 'Technical Round 1',
  '{{panelistName}}': 'Karthik Rajan',
  '{{interviewLink}}': 'https://meet.google.com/abc-defg-hij',
  '{{designation}}': 'Senior Software Engineer',
  '{{joiningDate}}': 'April 15, 2026',
  '{{annualCTC}}': '₹18,00,000',
  '{{offerExpiry}}': 'April 5, 2026',
  '{{department}}': 'Engineering',
  '{{companyName}}': 'SYNCRAZE Technologies Pvt Ltd',
  '{{companyAddress}}': '123 Tech Park, Chennai, Tamil Nadu - 600001',
  '{{hrName}}': 'Priya Menon',
  '{{hrEmail}}': 'hr@syncraze.com',
  '{{companyLogo}}': 'https://your-domain.com/logo.png',
  '{{companyWebsite}}': 'https://syncraze.com',
  '{{employeeName}}': 'Anbu Kumar',
  '{{employeeId}}': 'EMP-2026-042',
  '{{employeeEmail}}': 'anbu@syncraze.com',
  '{{managerName}}': 'Rajesh Murugan',
};
